/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Camera_Module_1: THREE.Mesh
    Camera_Module_2: THREE.Mesh
  }
  materials: {
    Plastic_Material: THREE.MeshStandardMaterial
    Glass_Material: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Camera_Module_GEO.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Camera_Module_1.geometry} material={materials.Plastic_Material} />
      <mesh geometry={nodes.Camera_Module_2.geometry} material={materials.Glass_Material} />
    </group>
  )
}

useGLTF.preload('/Camera_Module_GEO.glb')
